### ISSUE TITLE
NoSuchMethodError ... LightAdminRepositoryRestMvcConfiguration.entityLinks

### ISSUE THREAD

**Issue by dsteinkopf** [la-team/light-admin#211]
I am having a problem with the current version of lightadmin.
You can reproduce it exactly with the lightadmin-springboot example:

    git clone https://github.com/la-team/lightadmin-springboot.git
    cd lightadmin-springboot
    mvn package
    java -jar target/lightadmin-boot.jar

results in
```
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.lightadmin.core.web.json.DomainTypeToJsonMetadataConverter org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.domainTypeToJsonMetadataConverter()] threw exception; nested exception is java.lang.NoSuchMethodError: org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.entityLinks()Lorg/springframework/data/rest/webmvc/support/RepositoryEntityLinks;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188) ~[spring-beans-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
...
```

**Comment by dsteinkopf** [comment]
same problem when using snapshot build `<lightadmin.version>1.2.0.BUILD-SNAPSHOT</lightadmin.version>`

**Comment by max-dev** [comment]
@dsteinkopf, you're right. Reworking spring-boot apps is in progress

**Comment by max-dev** [comment]
@dsteinkopf Hi, I've just updated lightadmin-springboot application to use the latest LA.
Can you check the issue is closed now, please?

**Comment by max-dev** [comment]
Fixed according to #172

**Comment by dsteinkopf** [comment]
Confirmed. lightadmin-springboot example is now working for me, thank you. I will try in my own application, now.

**Comment by dsteinkopf** [comment]
In my spring boot application everything seems to work fine with currrent lightadmin-1.2.0.BUILD-SNAPSHOT from lightadmin-nexus-snapshots (see lightadmin-springboot example). Thank you again.
