### ISSUE TITLE
Spring Data Evans support

### ISSUE THREAD

**Issue by pentavalle** [la-team/light-admin#153]
Currently if using Spring Data Evans instead of Dijkstra I obtain this error during startup:

<code>
java.lang.NoSuchMethodError: org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.entityLinks()Lorg/springframework/hateoas/EntityLinks;
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.entityLinks(LightAdminRepositoryRestMvcConfiguration.java:68)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9.CGLIB$entityLinks$2(<generated>)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9$$FastClassBySpringCGLIB$$f1c17aff.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9.entityLinks(<generated>)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.entityLinks(LightAdminRepositoryRestMvcConfiguration.java:53)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9.CGLIB$entityLinks$1(<generated>)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9$$FastClassBySpringCGLIB$$f1c17aff.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$954ecad9.entityLinks(<generated>)
</code>

Considering you upgraded to Spring 4.1 in POMs, could you support even latest release of Spring Data?

**Comment by luj1985** [comment]
seems like ```spring-data-rest-mvc``` has changed the data type of ```entityLinks``` in ```org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration```, that make ```NoSuchMethodError``` happend

https://github.com/spring-projects/spring-data-rest/commit/3969c3494090eee1707a67d19bd88cf2d1c24abe

**Comment by lazaridis-com** [comment]
@luj1985, have you solved this finally on code-level?

I get the same error when updating the spring-boot version to 1.2.3.RELEASE, see

https://github.com/la-team/lightadmin-springboot/blob/master/pom.xml#L8

**Comment by lazaridis-com** [comment]
seems `org.lightadmin.core.web.support.DynamicRepositoryEntityLinks` and others, needs to be updated to work with `org.springframework.data.rest.webmvc.support.RepositoryEntityLinks` instead of `org.springframework.hateoas.EntityLinks`

**Comment by lubo08** [comment]
any update? will be this upgraded to be compatible with last spring boot release?

**Comment by lazaridis-com** [comment]
@lubo08 , I'm working on an update, see https://github.com/lazaridis-com/light-admin (spring-data-rest-2.3.0), with the goal to update to spring-boot and use of spring-platform-bom in general.

**Comment by lazaridis-com** [comment]
@pentavalle , @lubo08 

try with latest master (13f255a), should work now (with spring-boot-1.2.3)

**Comment by dsteinkopf** [comment]
this problem seems to be still existing and - if this is really the same problem - is reproducable in lightadmin-springboot example. see #211

**Comment by max-dev** [comment]
Hi, LightAdmin has been upgraded to use Spring Boot 1.2.3 ~> tested with https://github.com/la-team/lightadmin-springboot reference application.
